PRAGMA foreign_keys=off;
CREATE TABLE `__fajta`(
    faj_id INTEGER PRIMARY KEY AUTOINCREMENT,
    faj_nev TEXT NOT NULL
);
INSERT INTO `__fajta` (faj_nev) VALUES
('Abesszin'),
('Amerikai csonkafarkú'),
('Amerikai drótszőrű'),
('Amerikai görbefülű'),
('Amerikai rövidszőrű'),
('Arab mau'),
('Ausztrál ködmacska'),
('Balinéz'),
('Bambino'),
('Bengáli'),
('Birmán'),
('Bombay'),
('Brazil rövidszőrű'),
('Brit hosszúszőrű'),
('Brit rövidszőrű'),
('Burma'),
('Burmilla'),
('Chantilly-Tiffany'),
('Chausie'),
('Colorpoint rövidszőrű'),
('Cornish rex'),
('Cymric'),
('Ciprusi'),
('Devon rex'),
('Doni szfinx'),
('Dragon Li'),
('Egzotikus rövidszőrű'),
('Egyiptomi mau'),
('Európai rövidszőrű'),
('Havanna'),
('Házi hosszúszőrű'),
('Házi rövidszőrű'),
('Himalájai'),
('Hócipős'),
('Japán csonkafarkú'),
('Kaliforniai pettyes'),
('Kartaúzi'),
('Khao manee'),
('Keleti hosszúszőrű'),
('Keleti rövidszőrű'),
('Korat'),
('Kurili csonkafarkú'),
('LaPerm'),
('Lykoi'),
('Maine Coon'),
('Manx'),
('Minskin'),
('Munchkin'),
('Nebelung'),
('Norvég erdei'),
('Ocicat'),
('Orosz kék'),
('Perzsa'),
('Peterbald'),
('Pixie-bob'),
('Ragamuffin'),
('Ragdoll'),
('Selkirk rex'),
('Serengeti'),
('Skót lógófülű'),
('Sokoke'),
('Szavanna'),
('Szfinx'),
('Szibériai'),
('Sziámi'),
('Szingapúri'),
('Szomáli'),
('Thai'),
('Tonkinéz'),
('Toyger'),
('Török angóra'),
('Török van'),
('York csokoládé');
DROP TABLE `fajta`;
ALTER TABLE `__fajta` RENAME TO `fajta`;
PRAGMA foreign_keys=on;